import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { BarChart3, BriefcaseBusiness, ChevronDown, ExternalLink, ImagePlus, LayoutDashboard, LogOut, Mail, Menu, Pencil, Plus, Search, ShieldCheck, Trash2, Users, X } from 'lucide-react'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1'
type Portfolio = { id:number; name:string; category:string; description:string; website_url:string; image_url:string|null; updated_at?:string }
type Admin = { id:number; name:string; email:string; created_at:string }
type User = { id:number; name:string; email:string }

async function request(path:string, options:RequestInit = {}) {
  const token = localStorage.getItem('optibis_token'); const headers = new Headers(options.headers)
  if (!(options.body instanceof FormData)) headers.set('Content-Type','application/json')
  if (token) headers.set('Authorization', `Bearer ${token}`)
  const response = await fetch(`${API}${path}`, {...options, headers}); const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.message || Object.values(body.errors || {}).flat().join(' ') || 'Terjadi kesalahan.')
  return body
}

function Login({onLogin}:{onLogin:(user:User, token:string)=>void}) {
  const [email,setEmail] = useState('admin@optibis.test'), [password,setPassword] = useState('password123'), [error,setError] = useState(''), [busy,setBusy] = useState(false)
  async function submit(e:FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const data=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})}); onLogin(data.user,data.token) } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  return <main className="login-page"><div className="login-art"><div className="art-orb orb-one"/><div className="art-orb orb-two"/><div className="art-copy"><div className="brand-mark">O</div><p className="eyebrow">OPTIBIS STUDIO</p><h1>Bangun karya yang<br/><em>berkesan.</em></h1><p className="muted-light">Kelola portofolio digital Anda dalam satu ruang yang sederhana dan powerful.</p></div></div><div className="login-panel"><div className="mobile-brand"><div className="brand-mark">O</div><span>optibis</span></div><div className="login-box"><p className="eyebrow pink">ADMIN CONSOLE</p><h2>Selamat datang kembali</h2><p className="subtle">Masuk untuk mengelola portofolio dan tim Anda.</p><form onSubmit={submit}><label>Email<div className="input-wrap"><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="nama@perusahaan.com"/></div></label><label>Password<div className="input-wrap"><ShieldCheck size={17}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/></div></label>{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Memproses…':'Masuk ke dashboard'} <ChevronDown size={17} className="rotate-270"/></button></form><p className="login-hint">Demo: admin@optibis.test · password123</p></div><div className="login-footer">© 2025 Optibis Studio <span>·</span> Built with intention</div></div></main>
}

function App() {
  const [user,setUser] = useState<User|null>(null), [section,setSection] = useState<'portfolio'|'admins'>('portfolio'), [menu,setMenu] = useState(false)
  useEffect(()=>{ const token=localStorage.getItem('optibis_token'); if(token) request('/auth/me').then(d=>setUser(d.user)).catch(()=>localStorage.removeItem('optibis_token')) },[])
  if(!user) return <Login onLogin={(u,t)=>{localStorage.setItem('optibis_token',t);setUser(u)}}/>
  function logout(){ request('/auth/logout',{method:'POST'}).catch(()=>{}).finally(()=>{localStorage.removeItem('optibis_token');setUser(null)}) }
  return <div className="shell"><aside className={menu?'open':''}><div className="side-brand"><div className="brand-mark">O</div><span>optibis</span></div><div className="workspace"><span className="avatar">{user.name[0]}</span><div><strong>{user.name}</strong><small>Administrator</small></div><ChevronDown size={15}/></div><nav><p className="nav-label">WORKSPACE</p><button className={section==='portfolio'?'active':''} onClick={()=>{setSection('portfolio');setMenu(false)}}><LayoutDashboard size={18}/> Portofolio</button><button className={section==='admins'?'active':''} onClick={()=>{setSection('admins');setMenu(false)}}><Users size={18}/> Admin <span className="nav-dot">•</span></button></nav><div className="sidebar-bottom"><div className="side-tip"><BarChart3 size={18}/><div><b>Keep creating</b><small>Ide bagus selalu layak dibuat.</small></div></div><button className="logout" onClick={logout}><LogOut size={17}/> Keluar</button></div></aside><div className="main"><header><button className="menu-btn" onClick={()=>setMenu(!menu)}><Menu/></button><div className="crumb"><span>Workspace</span><b>/</b><strong>{section==='portfolio'?'Portofolio':'Admin'}</strong></div><div className="header-actions"><span className="status"><i/> Sistem online</span><button className="profile" onClick={logout}><span className="avatar">{user.name[0]}</span><ChevronDown size={15}/></button></div></header>{section==='portfolio'?<PortfolioView/>:<AdminView currentUser={user}/>}</div></div>
}

function PortfolioView(){ const [items,setItems]=useState<Portfolio[]>([]), [query,setQuery]=useState(''), [editing,setEditing]=useState<Portfolio|null|false>(false), [refresh,setRefresh]=useState(0), [error,setError]=useState(''); useEffect(()=>{request('/portfolios').then(setItems).catch(e=>setError(e.message))},[refresh]); const filtered=items.filter(x=>(x.name+x.category).toLowerCase().includes(query.toLowerCase())); async function remove(id:number){if(!confirm('Hapus portofolio ini?'))return; try{await request('/portfolios/'+id,{method:'DELETE'});setRefresh(x=>x+1)}catch(e){setError((e as Error).message)}} return <section className="content"><div className="page-title"><div><p className="eyebrow pink">CONTENT LIBRARY</p><h1>Portofolio</h1><p className="subtle">Tampilkan karya terbaik dan kisah di baliknya.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/> Tambah portofolio</button></div><div className="stats"><div><span>Total karya</span><b>{items.length}</b><small>Semua portofolio</small></div><div><span>Kategori</span><b>{new Set(items.map(x=>x.category)).size}</b><small>Jenis layanan</small></div><div><span>Terakhir diperbarui</span><b className="date-stat">{items[0]?.updated_at?new Date(items[0].updated_at).toLocaleDateString('id-ID',{day:'2-digit',month:'short'}):'—'}</b><small>Update terbaru</small></div></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Cari portofolio…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="result-count">{filtered.length} karya</span></div>{error&&<div className="error-box">{error}</div>}<div className="portfolio-grid">{filtered.map(item=><article className="portfolio-card" key={item.id}><div className="card-image">{item.image_url?<img src={item.image_url} alt=""/>:<div className="image-placeholder"><BriefcaseBusiness size={26}/><span>{item.category}</span></div>}<span className="category">{item.category}</span><div className="card-hover"><button onClick={()=>setEditing(item)}><Pencil size={16}/></button><button onClick={()=>remove(item.id)}><Trash2 size={16}/></button></div></div><div className="card-body"><h3>{item.name}</h3><p>{item.description}</p><a href={item.website_url} target="_blank">Lihat website <ExternalLink size={14}/></a></div></article>)}{!filtered.length&&<div className="empty"><BriefcaseBusiness size={30}/><p>Belum ada portofolio.</p></div>}</div>{editing!==false&&<PortfolioModal item={editing} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);setRefresh(x=>x+1)}}/>}</section> }

function PortfolioModal({item,onClose,onSaved}:{item:Portfolio|null,onClose:()=>void,onSaved:()=>void}){const [form,setForm]=useState({name:item?.name||'',category:item?.category||'',description:item?.description||'',website_url:item?.website_url||''}), [image,setImage]=useState<File|null>(null), [error,setError]=useState(''), [busy,setBusy]=useState(false);async function save(e:FormEvent){e.preventDefault();setBusy(true);const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,v));if(image)data.append('image',image);if(item)data.append('_method','PUT');try{await request(item?`/portfolios/${item.id}`:'/portfolios',{method:'POST',body:data});onSaved()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow pink">{item?'EDIT':'NEW ENTRY'}</p><h2>{item?'Edit portofolio':'Tambah portofolio'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div><label>Nama website<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><div className="form-row"><label>Kategori<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/></label><label>Link website<input type="url" value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})} required/></label></div><label>Deskripsi<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label className="upload">Gambar <span><ImagePlus size={18}/> {image?.name||'Pilih gambar (maks. 5 MB)'}<input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)}/></span></label>{error&&<div className="error-box">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan portofolio'}</button></div></form></div>}

function AdminView({currentUser}:{currentUser:User}){const [items,setItems]=useState<Admin[]>([]), [editing,setEditing]=useState<Admin|null|false>(false), [refresh,setRefresh]=useState(0), [error,setError]=useState('');useEffect(()=>{request('/admins').then(setItems).catch(e=>setError(e.message))},[refresh]);async function remove(id:number){if(!confirm('Hapus admin ini?'))return;try{await request('/admins/'+id,{method:'DELETE'});setRefresh(x=>x+1)}catch(e){setError((e as Error).message)}}return <section className="content"><div className="page-title"><div><p className="eyebrow pink">TEAM ACCESS</p><h1>Admin</h1><p className="subtle">Kelola siapa saja yang punya akses ke workspace.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/> Tambah admin</button></div><div className="admin-table"><div className="table-head"><span>Nama</span><span>Email</span><span>Bergabung</span><span></span></div>{items.map(item=><div className="table-row" key={item.id}><div className="person"><span className="avatar">{item.name[0]}</span><div><b>{item.name}</b>{item.id===currentUser.id&&<small>Anda</small>}</div></div><span>{item.email}</span><span>{new Date(item.created_at).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</span><div className="row-actions"><button onClick={()=>setEditing(item)}><Pencil size={16}/></button><button onClick={()=>remove(item.id)}><Trash2 size={16}/></button></div></div>)}{!items.length&&<div className="empty">Belum ada admin.</div>}</div>{error&&<div className="error-box">{error}</div>}{editing!==false&&<AdminModal item={editing} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);setRefresh(x=>x+1)}}/>}</section>}
function AdminModal({item,onClose,onSaved}:{item:Admin|null,onClose:()=>void,onSaved:()=>void}){const [form,setForm]=useState({name:item?.name||'',email:item?.email||'',password:''}), [error,setError]=useState(''), [busy,setBusy]=useState(false);async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const body={...form};if(!body.password)delete (body as Partial<typeof body>).password;await request(item?`/admins/${item.id}`:'/admins',{method:item?'PUT':'POST',body:JSON.stringify(body)});onSaved()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="modal small-modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow pink">{item?'EDIT ADMIN':'TEAM ACCESS'}</p><h2>{item?'Edit admin':'Tambah admin'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div><label>Nama lengkap<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={item?'Kosongkan jika tidak berubah':'Min. 8 karakter'} required={!item}/></label>{error&&<div className="error-box">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan admin'}</button></div></form></div>}
export default App
