import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

const TEXT_TRANSLATIONS = {
  Beranda: "Home",
  Layanan: "Services",
  Paket: "Packages",
  Portofolio: "Portfolio",
  Konten: "Content",
  Tentang: "About",
  "Pilar Layanan": "Service Pillars",
  "Berdasarkan Kebutuhan": "By Business Need",
  "Memulai Bisnis": "Start a Business",
  "Meningkatkan Citra Bisnis": "Improve Business Image",
  "Meningkatkan Citra": "Improve Brand Image",
  "Membuat Website": "Build a Website",
  "Mendapatkan Leads": "Generate Leads",
  "Mengelola Digital Bulanan": "Monthly Digital Management",
  "Karya & Tools": "Work & Tools",
  "Portofolio Proyek": "Project Portfolio",
  "Tools & Platform": "Tools & Platforms",
  "Industri Kami": "Our Industries",
  "Testimoni Klien": "Client Testimonials",
  "Jelajah Konten": "Explore Content",
  "Semua Konten": "All Content",
  Trending: "Trending",
  "Short Video": "Short Videos",
  "Video & Podcast": "Videos & Podcasts",
  "Cari Konten": "Search Content",
  "Produk Digital": "Digital Products",
  "Ebook & Pelatihan": "Ebooks & Training",
  "Konsultasi Berbayar": "Paid Consultation",
  "Tools & Template": "Tools & Templates",
  Perusahaan: "Company",
  "Tentang Optibis": "About Optibis",
  "Proses Kerja": "Our Process",
  "Tim Kami": "Our Team",
  "Hubungi Kami": "Contact Us",
  "Konsultasi Gratis": "Free Consultation",
  "Chat WhatsApp": "WhatsApp Chat",
  "Lokasi Kantor": "Office Location",
  Konsultasi: "Consultation",
  "Lihat Paket": "View Packages",
  "Pilih Paket": "Choose Package",
  "Paket Website": "Website Packages",
  "Paket Bulanan": "Monthly Packages",
  "Paket Digital Asset": "Digital Asset Packages",
  Populer: "Popular",
  "Mulai dari": "Starting from",
  "Pelajari Lebih Lanjut": "Learn More",
  "Rekomendasi Paket Lainnya": "Other Recommended Packages",
  "Berita Trending": "Trending News",
  "Lihat semua paket": "View all packages",
  "Lihat semua": "View all",
  "Tiga Pilar": "Three Pillars",
  Solusi: "Solutions",
  Bantuan: "Support",
  "Tentang Kami": "About Us",
  Kontak: "Contact",
  "Kebijakan Privasi": "Privacy Policy",
  "Syarat & Ketentuan": "Terms & Conditions",
  "Cari Leads": "Find Leads",
  "Kelola Digital": "Manage Digital",
  "Multi-Cabang": "Multi-Branch",
  "Bahasa Indonesia": "Indonesian",
  "Yang Termasuk dalam Layanan": "What's Included",
  "Konsultasikan Layanan": "Discuss This Service",
  "Layanan tidak ditemukan": "Service Not Found",
  "Kembali ke Beranda": "Back to Home",
  "DIGITAL SOLUTION PARTNER": "DIGITAL SOLUTIONS PARTNER",
  "Satu Partner untuk": "One Partner for",
  "Satu Partner untuk Pertumbuhan Digital Bisnis Anda": "One Partner for Your Business' Digital Growth",
  "Bangun Brand,": "Build Your Brand,",
  "dan Pertumbuhan Digital Bisnis Anda!": "and Grow Your Business Digitally!",
  dan: "and",
  "Pertumbuhan Digital": "Digital Growth",
  "Bisnis Anda": "Your Business",
  "Optibis membantu bisnis tampil lebih profesional, mudah ditemukan, dan bertumbuh secara digital melalui solusi yang terintegrasi dan mudah dipahami.": "Optibis helps businesses look more professional, get discovered, and grow digitally through integrated, easy-to-understand solutions.",
  "Lihat Semua Solusi": "View All Solutions",
  "Layanan Optibis": "Optibis Services",
  "Solusi Digital untuk Setiap Tahap Bisnis": "Digital Solutions for Every Stage of Business",
  "Dari membangun brand hingga mengelola pertumbuhan digital, pilih layanan yang paling sesuai dengan kebutuhan bisnis Anda.": "From building your brand to managing digital growth, choose the services that best fit your business needs.",
  "Paket Optibis": "Optibis Packages",
  "Paket Digital yang Siap Disesuaikan": "Flexible Digital Packages for Your Business",
  "Pilih paket sesuai kebutuhan dan budget bisnis Anda. Semua paket dapat disesuaikan bersama tim Optibis.": "Choose a package that fits your business needs and budget. Every package can be tailored with the Optibis team.",
  "Karya & Solusi Digital Terbaik Kami": "Our Best Digital Work and Solutions",
  "Eksplorasi berbagai proyek digital yang telah kami selesaikan untuk membantu bisnis bertransformasi dan berkembang.": "Explore the digital projects we have delivered to help businesses transform and grow.",
  "Jelajahi Layanan": "Explore Services",
  "Pilih Jalur Layanan yang Tepat": "Choose the Right Service Path",
  "Mulai berdasarkan pilar keahlian atau kebutuhan utama bisnis Anda saat ini.": "Start with an area of expertise or your business's most important need today.",
  "Semua Paket": "All Packages",
  "Temukan Paket Sesuai Kebutuhan Bisnis": "Find a Package for Your Business Needs",
  "Bandingkan paket dari tiga pilar Optibis dan buka detail paket yang ingin Anda pelajari.": "Compare packages across Optibis' three pillars and explore the details that matter to you.",
  "Eksplorasi Optibis": "Explore Optibis",
  "Jelajahi Karya, Tools, dan Resource Kami": "Explore Our Work, Tools, and Resources",
  "Temukan proyek, platform, materi resmi, industri yang kami layani, dan pengalaman klien Optibis.": "Discover our projects, platforms, official resources, served industries, and client experiences.",
  "Materi & Insight": "Resources & Insights",
  "Pilar Optibis": "Optibis Pillars",
  "Katalog Layanan": "Service Catalog",
  "Solusi Bisnis": "Business Solutions",
  "Resource Gratis": "Free Resources",
  "Bantuan Optibis": "Optibis Support",
  "Tantangan Bisnis": "Business Challenges",
  "Website Optibis": "Optibis Websites",
  "Mulai Bersama Optibis": "Start with Optibis",
  "FAQ Optibis": "Optibis FAQ",
  "Tambahan Opsional": "Optional Add-ons",
  "Keunggulan Paket": "Package Benefits",
  "Portofolio Pilar Ini": "This Pillar's Portfolio",
  "Paket Pilihan": "Selected Packages",
  "Insight Terbaru": "Latest Insights",
  "Konsultasi Optibis": "Optibis Consultation",
  "Apa Kata Klien Tentang Optibis": "What Clients Say About Optibis",
  "Pengalaman nyata bisnis yang tumbuh bersama layanan digital Optibis.": "Real experiences from businesses growing with Optibis digital services.",
  "Membantu Bisnis Tampil Lebih Profesional dan Bertumbuh": "Helping Businesses Look More Professional and Grow",
  "Kami percaya solusi digital yang baik harus mudah dipahami, mudah dikelola, dan relevan dengan tujuan bisnis. Karena itu, kami bekerja sebagai partner yang mendampingi dari perencanaan hingga pertumbuhan.": "We believe good digital solutions should be easy to understand, easy to manage, and relevant to business goals. That is why we work as a partner from planning through growth.",
  "Satu Partner, Tiga Pilar": "One Partner, Three Pillars",
  "Dari membangun identitas hingga mengelola pertumbuhan digital, kebutuhan bisnis Anda ditangani dalam satu ekosistem yang terarah.": "From building your identity to managing digital growth, your business needs are handled in one focused ecosystem.",
  "Cara Kami Bekerja": "How We Work",
  "Pendekatan yang kolaboratif, transparan, dan berorientasi pada hasil bisnis.": "A collaborative, transparent, and business-results-oriented approach.",
  "Fokus pada Pertumbuhan": "Focused on Growth",
  "Setiap rekomendasi kami diarahkan pada tujuan bisnis dan hasil yang dapat diukur.": "Every recommendation is tied to business goals and measurable outcomes.",
  "Solusi yang Terintegrasi": "Integrated Solutions",
  "Branding, website, dan pengelolaan digital dirancang untuk saling memperkuat.": "Branding, websites, and digital management are designed to reinforce one another.",
  "Partner yang Transparan": "A Transparent Partner",
  "Proses kerja, timeline, dan deliverables disampaikan dengan jelas sejak awal.": "Our process, timeline, and deliverables are clear from the start.",
  "Memahami Bisnis Anda": "Understanding Your Business",
  "Kami memulai dari konteks, tantangan, dan karakter bisnis Anda sebelum menyusun solusi.": "We start with your business context, challenges, and character before shaping a solution.",
  "Tim Digital Lengkap untuk Bisnis Anda": "A Complete Digital Team for Your Business",
  "Keahlian lintas disiplin yang bekerja bersama untuk menghadirkan solusi digital yang konsisten dan terintegrasi.": "Cross-disciplinary expertise working together to deliver consistent, integrated digital solutions.",
  "Brand & Creative": "Brand & Creative",
  "Membangun identitas brand, materi promosi, dan komunikasi visual yang konsisten.": "Building consistent brand identities, promotional assets, and visual communication.",
  "Website & Technology": "Website & Technology",
  "Merancang website profesional, mudah dikelola, dan mendukung kebutuhan bisnis.": "Designing professional, manageable websites that support business needs.",
  "Growth & Strategy": "Growth & Strategy",
  "Mengelola strategi, konten, SEO, iklan, dan laporan performa secara terarah.": "Managing strategy, content, SEO, advertising, and performance reporting with a clear direction.",
  "Mari Diskusikan Kebutuhan Bisnis Anda": "Let's Discuss Your Business Needs",
  "Pilih cara yang paling nyaman untuk terhubung dengan tim Optibis.": "Choose the most convenient way to connect with the Optibis team.",
  "Hubungi konsultan Optibis untuk mendiskusikan kebutuhan bisnis Anda secara langsung.": "Contact an Optibis consultant to discuss your business needs directly.",
  "Indonesia - melayani kebutuhan digital bisnis dari berbagai wilayah secara online.": "Indonesia - serving businesses across the country through online collaboration.",
  "Branding lebih rapi": "Stronger branding",
  "Website lebih profesional": "A more professional website",
  "Konten lebih konsisten": "More consistent content",
  "Leads lebih tertata": "Better organized leads",
  "Performa mudah dipantau": "Easy performance tracking",
  "Support lebih cepat": "Faster support",
  "Proyek Selesai": "Projects Completed",
  Klien: "Clients",
  "Klien Aktif": "Active Clients",
  "Industri Dilayani": "Industries Served",
  "Tahun Pengalaman": "Years of Experience",
  "Rating Klien": "Client Rating",
  "Repeat Order": "Repeat Orders",
  "Apakah Bisnis Anda Mengalami Hal Ini?": "Is Your Business Facing Any of These Challenges?",
  "Banyak bisnis menghadapi tantangan serupa. Optibis hadir untuk menyelesaikan semuanya dalam satu solusi terpadu.": "Many businesses face the same challenges. Optibis brings everything together in one integrated solution.",
  "Branding belum rapi": "Inconsistent branding",
  "Logo, warna, dan materi promosi belum konsisten sehingga bisnis terlihat kurang profesional.": "Your logo, colors, and promotional materials are inconsistent, making the business look less professional.",
  "Website belum profesional": "An unprofessional website",
  "Belum punya website atau website yang ada sudah ketinggalan zaman dan sulit dikelola.": "You either do not have a website yet, or the current one is outdated and hard to manage.",
  "Sulit ditemukan di Google": "Hard to find on Google",
  "Bisnis Anda tidak muncul saat calon pelanggan mencari layanan yang Anda tawarkan.": "Your business does not appear when potential customers search for the services you offer.",
  "Konten tidak rutin": "Irregular content",
  "Media sosial jarang update karena tidak ada tim yang mengelola konten secara konsisten.": "Social media is rarely updated because no team manages content consistently.",
  "Tim internal kewalahan": "An overwhelmed internal team",
  "Tim Anda harus mengerjakan banyak hal sekaligus dan tidak fokus pada pekerjaan utama.": "Your team handles too many things at once and cannot focus on its core work.",
  "Materi promosi tidak konsisten": "Inconsistent promotional materials",
  "Setiap materi terlihat berbeda karena tidak ada panduan brand yang jelas.": "Every asset looks different because there is no clear brand guideline.",
  "Leads tidak tertata": "Disorganized leads",
  "Data calon pelanggan tersebar di banyak tempat dan sulit ditindaklanjuti.": "Prospect data is scattered across multiple places and difficult to follow up.",
  "Tidak ada laporan performa": "No performance reporting",
  "Tidak tahu mana strategi yang berhasil karena tidak ada laporan yang jelas.": "It is unclear which strategies work because there is no reliable reporting.",
  "Optibis menyatukan kebutuhan branding, website, dan pengelolaan digital dalam": "Optibis brings branding, websites, and digital management together with",
  "satu partner": "one partner",
  "3 Pilar Utama Optibis": "Optibis' 3 Core Pillars",
  "Tiga kompetensi utama yang saling melengkapi untuk membantu bisnis Anda dari membangun identitas hingga mengelola pertumbuhan digital.": "Three complementary capabilities that help your business build its identity and manage digital growth.",
  "PILAR 1": "PILLAR 1",
  "PILAR 2": "PILLAR 2",
  "PILAR 3": "PILLAR 3",
  "Bangun citra bisnis yang profesional": "Build a professional business image",
  "Miliki website yang bekerja untuk bisnis": "Get a website that works for your business",
  "Punya tim digital tanpa harus merekrut sendiri": "Get a digital team without hiring one yourself",
  "Dari logo, brand guideline, company profile, hingga materi promosi — semua aset yang dibutuhkan bisnis Anda untuk tampil konsisten dan dipercaya.": "From logos and brand guidelines to company profiles and promotional materials, get every asset your business needs to look consistent and credible.",
  "Website yang membantu bisnis Anda ditemukan, dipercaya, dihubungi, dan dikelola dengan lebih mudah — dari landing page hingga sistem terintegrasi.": "A website that helps your business get discovered, earn trust, receive inquiries, and operate more easily, from landing pages to integrated systems.",
  "Tim digital lengkap yang mengelola konten, media sosial, SEO, iklan, dan laporan performa bisnis Anda secara konsisten setiap bulan.": "A complete digital team that consistently manages your content, social media, SEO, ads, and performance reports every month.",
  Lihat: "View",
  "Stationery Bisnis": "Business Stationery",
  "Video Profile": "Company Video",
  "Semua Kebutuhan Digital Bisnis dalam Satu Tempat": "Every Digital Business Need in One Place",
  "Pilih layanan yang sesuai dengan kebutuhan bisnis Anda — dari branding, website, hingga pengelolaan digital bulanan.": "Choose the service that fits your business, from branding and websites to ongoing digital management.",
  "Logo, brand guideline, dan seluruh identitas visual bisnis Anda.": "Logo, brand guidelines, and your complete business visual identity.",
  "Kartu nama, kop surat, invoice, dan dokumen bisnis profesional.": "Business cards, letterheads, invoices, and professional business documents.",
  "Company profile, pitch deck, brosur, katalog, dan materi penjualan.": "Company profiles, pitch decks, brochures, catalogs, and sales materials.",
  "Template feed, story, highlight, dan seluruh visual media sosial.": "Feed, story, and highlight templates plus complete social media visuals.",
  "Copywriting, artikel, video promosi, foto produk, dan konten digital.": "Copywriting, articles, promotional videos, product photography, and digital content.",
  "Email bisnis, Google Business, WhatsApp Business, dan akun digital.": "Business email, Google Business, WhatsApp Business, and digital account setup.",
  "Halaman fokus untuk promosi, event, campaign, atau lead generation.": "A focused page for promotions, events, campaigns, or lead generation.",
  "Website company profile, corporate, portfolio, dan layanan profesional.": "Company profile, corporate, portfolio, and professional service websites.",
  "Website custom dengan CMS, CRM, booking, dan sistem terintegrasi.": "A custom website with CMS, CRM, booking, and integrated systems.",
  "Redesign, remake, optimasi kecepatan, SEO, dan konversi website.": "Website redesign, rebuild, speed optimization, SEO, and conversion improvements.",
  "Update berkala, backup, keamanan, dan dukungan teknis website.": "Regular updates, backups, security, and technical website support.",
  "Toko online, booking, membership, directory, dan multi-cabang.": "Online stores, booking, membership, directories, and multi-branch systems.",
  "Strategi & Planning": "Strategy & Planning",
  "Digital audit, riset kompetitor, content strategy, dan monthly roadmap.": "Digital audits, competitor research, content strategy, and monthly roadmaps.",
  "Kalender konten, desain, copywriting, reels, artikel, dan publishing.": "Content calendars, design, copywriting, reels, articles, and publishing.",
  "Posting, scheduling, monitoring, dan reporting media sosial.": "Social media posting, scheduling, monitoring, and reporting.",
  "Update konten, maintenance, blog, dan monitoring performa website.": "Content updates, maintenance, blogging, and website performance monitoring.",
  "SEO on-page, local SEO, Google Business, dan monitoring keyword.": "On-page SEO, local SEO, Google Business, and keyword monitoring.",
  "Meta Ads, Google Ads, TikTok Ads, creative, dan campaign reporting.": "Meta Ads, Google Ads, TikTok Ads, creative production, and campaign reporting.",
  "Pilih Solusi Berdasarkan Kondisi Bisnis Anda": "Choose a Solution for Your Current Business Stage",
  "Setiap bisnis punya kebutuhan berbeda. Pilih solusi yang paling sesuai dengan kondisi dan tujuan bisnis Anda saat ini.": "Every business has different needs. Choose the solution that best matches your current situation and goals.",
  "Logo, identitas, landing page, email bisnis, akun digital, dan konten launching.": "Logo, identity, landing page, business email, digital accounts, and launch content.",
  "Brand refresh, company profile, marketing kit, website, Google Business, dan sales assets.": "Brand refresh, company profile, marketing kit, website, Google Business, and sales assets.",
  "Landing page, campaign assets, form, WhatsApp, ads setup, dan lead reporting.": "Landing page, campaign assets, forms, WhatsApp, ad setup, and lead reporting.",
  "Content management, social media, website update, SEO, campaign, dan reporting.": "Content management, social media, website updates, SEO, campaigns, and reporting.",
  "Brand standardization, multi-location website, Google Business per cabang, dan central reporting.": "Brand standardization, multi-location websites, Google Business for each branch, and centralized reporting.",
  "Corporate branding, company profile, corporate website, campaign, maintenance, dan custom integration.": "Corporate branding, company profiles, corporate websites, campaigns, maintenance, and custom integrations.",
  "Paket Unggulan": "Featured Packages",
  "Pilih paket yang sesuai kebutuhan dan budget bisnis Anda. Semua paket dapat disesuaikan.": "Choose a package that fits your needs and budget. Every package can be customized.",
  "Paling Populer": "Most Popular",
  "Lihat Detail": "View Details",
  "Konsultasi Paket": "Discuss Package",
  "Siap Usaha": "Business Ready",
  "Citra Usaha": "Business Image",
  "Bisnis Profesional": "Professional Business",
  "Bisnis baru & UMKM yang baru memulai": "New businesses and early-stage SMEs",
  "Bisnis yang ingin tampil lebih profesional": "Businesses ready to look more professional",
  "Bisnis berkembang & corporate": "Growing businesses and corporations",
  "Promosi & campaign": "Promotions and campaigns",
  "Bisnis yang butuh sistem": "Businesses that need integrated systems",
  "UMKM & bisnis kecil": "SMEs and small businesses",
  "Bisnis berkembang": "Growing businesses",
  "Bisnis yang serius bertumbuh": "Businesses serious about growth",
  "Kartu Nama": "Business Cards",
  "Email Bisnis": "Business Email",
  "5x Revisi": "5 Revisions",
  "8x Revisi": "8 Revisions",
  "Stationery Lengkap": "Complete Stationery",
  "Template Presentasi": "Presentation Templates",
  "Unlimited Revisi Minor": "Unlimited Minor Revisions",
  "1 Halaman Landing Page": "1 Landing Page",
  "SEO Dasar": "Basic SEO",
  "Hosting 1 Tahun": "1 Year Hosting",
  "Multi Halaman": "Multiple Pages",
  "CMS Sederhana": "Simple CMS",
  "Form Kontak": "Contact Form",
  "Maintenance 3 Bulan": "3 Months Maintenance",
  "Dashboard Admin": "Admin Dashboard",
  "CRM Ringan": "Lightweight CRM",
  "Lead Management": "Lead Management",
  "12 Konten/Bulan": "12 Posts/Month",
  "2 Platform": "2 Platforms",
  "24 Konten/Bulan": "24 Posts/Month",
  "3 Platform": "3 Platforms",
  "40 Konten/Bulan": "40 Posts/Month",
  "Lihat Hasil Pekerjaan Kami": "See Our Work",
  "Portofolio pilihan dari berbagai industri dan layanan yang telah kami kerjakan.": "Selected work across the industries and services we have supported.",
  Semua: "All",
  "Konsultasi Proyek": "Discuss a Project",
  "Website yang Tidak Hanya Menarik, tetapi Juga": "A Website That Looks Great and Is",
  "Mudah Digunakan": "Easy to Use",
  "Kami membangun website yang tidak hanya cantik dilihat, tetapi juga mudah dikelola oleh tim Anda — lengkap dengan dashboard, CMS, dan sistem monitoring.": "We build websites that look polished and are easy for your team to manage, complete with dashboards, CMS, and monitoring systems.",
  "Mudah diperbarui": "Easy to update",
  "Mudah digunakan tim": "Easy for your team to use",
  "Mudah memantau leads": "Easy lead monitoring",
  "Mudah melihat perkembangan": "Easy progress tracking",
  "Aman dan responsif": "Secure and responsive",
  "Lihat Detail Website": "Explore Website Services",
  "Tim Digital Lengkap untuk Menjaga Bisnis Anda Tetap Aktif": "A Complete Digital Team to Keep Your Business Active",
  "Tidak perlu merekrut banyak karyawan untuk mengelola digital bisnis Anda. Serahkan pada Optibis.": "You do not need to hire a large team to manage your digital presence. Leave it to Optibis.",
  "Konten konsisten": "Consistent content",
  "Konten terbit rutin sesuai jadwal yang terencana.": "Content is published consistently on a planned schedule.",
  "Website terawat": "A well-maintained website",
  "Update berkala, monitoring performa, dan perbaikan.": "Regular updates, performance monitoring, and improvements.",
  "Promosi lebih aktif": "More active promotions",
  "Campaign dan iklan dikelola secara profesional.": "Campaigns and ads are managed professionally.",
  "Laporan lebih jelas": "Clearer reports",
  "Laporan performa bulanan yang mudah dipahami.": "Easy-to-understand monthly performance reports.",
  "Tim lebih hemat": "A more cost-efficient team",
  "Tanpa biaya rekrutmen, training, dan benefit karyawan.": "No recruitment, training, or employee benefit costs.",
  "Fokus bisnis terjaga": "Stay focused on the business",
  "Serahkan urusan digital, fokus pada bisnis inti.": "Delegate digital work and focus on your core business.",
  "Rata-rata hasil klien setelah 3 bulan": "Average client results after 3 months",
  "Lihat Paket Bulanan": "View Monthly Packages",
  "Jadwalkan Konsultasi": "Schedule a Consultation",
  "Solusi Digital untuk Berbagai Industri": "Digital Solutions for Every Industry",
  "Kami memahami kebutuhan unik setiap industri dan menyediakan solusi yang tepat sasaran. Klik untuk melihat detail tantangan & solusinya.": "We understand the unique needs of every industry and deliver focused solutions. Select an industry to see its challenges and solutions.",
  Properti: "Property",
  Kesehatan: "Healthcare",
  Pendidikan: "Education",
  Kuliner: "Food & Beverage",
  Kontraktor: "Contractors",
  Distributor: "Distribution",
  Organisasi: "Organizations",
  "Travel, umrah, wisata religi": "Travel, umrah, and religious tourism",
  "Real estate, developer, agen": "Real estate, developers, and agents",
  "Klinik, dokter, dental, wellness": "Clinics, doctors, dental, and wellness",
  "Sekolah, kursus, training": "Schools, courses, and training",
  "Restoran, coffee shop, catering": "Restaurants, coffee shops, and catering",
  "Interior, arsitektur, konstruksi": "Interior, architecture, and construction",
  "Retail, manufaktur, supplier": "Retail, manufacturing, and suppliers",
  "Konsultan, trainer, pembicara": "Consultants, trainers, and speakers",
  "Perusahaan besar, holding": "Large companies and holdings",
  "Yayasan, komunitas, NGO": "Foundations, communities, and NGOs",
  "Franchise, chain, multi-brand": "Franchises, chains, and multi-brand businesses",
  "Konsultasi Industri Anda": "Discuss Your Industry",
  "Tantangan yang Sering Dihadapi": "Common Challenges",
  "Solusi dari Optibis": "Solutions from Optibis",
  "Layanan yang Direkomendasikan": "Recommended Services",
  "Konsultasi untuk Industri": "Consultation for the",
  "Cara Kerja Optibis": "How Optibis Works",
  "Lima langkah sederhana untuk memulai transformasi digital bisnis Anda.": "Five simple steps to begin your business's digital transformation.",
  "Ceritakan kebutuhan bisnis Anda. Kami dengarkan, pahami, dan analisa bersama.": "Tell us what your business needs. We listen, understand, and assess it with you.",
  "Rekomendasi Solusi": "Solution Recommendation",
  "Kami berikan rekomendasi solusi, paket, dan estimasi yang paling sesuai.": "We recommend the most suitable solution, package, and estimate.",
  Perencanaan: "Planning",
  "Menyusun timeline, deliverables, dan milestone yang jelas dan transparan.": "We set a clear, transparent timeline, deliverables, and milestones.",
  "Produksi & Review": "Production & Review",
  "Tim kami mengerjakan, Anda mereview. Revisi sampai hasilnya sesuai harapan.": "Our team creates, you review, and we refine the work until it meets expectations.",
  "Launch & Support": "Launch & Support",
  "Project diluncurkan dengan dukungan penuh. Kami tetap mendampingi setelahnya.": "Your project launches with full support, and we continue to assist afterward.",
  "Mulai Konsultasi": "Start a Consultation",
  "Mulai dari Sini": "Start Here",
  "Belum yakin mulai dari mana? Coba salah satu resource gratis dari Optibis.": "Not sure where to begin? Try one of Optibis' free resources.",
  "Audit Digital Gratis": "Free Digital Audit",
  "Evaluasi kehadiran digital bisnis Anda secara menyeluruh.": "Get a complete review of your business's digital presence.",
  "Audit Website": "Website Audit",
  "Cek performa, keamanan, dan potensi perbaikan website Anda.": "Review your website's performance, security, and improvement opportunities.",
  "Checklist Branding": "Branding Checklist",
  "Panduan lengkap untuk memastikan branding bisnis Anda sudah rapi.": "A complete guide to make sure your business branding is polished.",
  "Rekomendasi Paket": "Package Recommendation",
  "Dapatkan rekomendasi paket yang tepat untuk kebutuhan Anda.": "Get the right package recommendation for your needs.",
  "Kalkulator Estimasi": "Estimate Calculator",
  "Hitung perkiraan biaya untuk project digital Anda.": "Estimate the cost of your digital project.",
  "Unduh profil perusahaan Optibis dalam format PDF.": "Download the Optibis company profile in PDF format.",
  "Akses Gratis": "Free Access",
  "Profil Google Bisnis": "Google Business Profile",
  "Informasi resmi & ulasan dari Google": "Official information and reviews from Google",
  ulasan: "reviews",
  Rute: "Directions",
  "Senin - Jumat": "Monday - Friday",
  "Ulasan Google": "Google Reviews",
  "Pertanyaan Umum & Konsultasi Gratis": "Frequently Asked Questions & Free Consultation",
  "Temukan jawaban cepat atau langsung hubungi kami untuk konsultasi gratis.": "Find quick answers or contact us directly for a free consultation.",
  "Apa itu Optibis?": "What is Optibis?",
  "Optibis adalah digital solution partner yang membantu bisnis dalam tiga area utama: branding melalui Digital Asset, website melalui layanan Website, dan pengelolaan digital bulanan melalui Digital Growth Team.": "Optibis is a digital solutions partner supporting businesses in three core areas: branding through Digital Asset, websites through Website services, and ongoing digital management through the Digital Growth Team.",
  "Layanan apa saja yang tersedia?": "What services are available?",
  "Optibis menyediakan layanan pembuatan identitas brand, desain marketing materials, pembuatan website (dari landing page hingga custom system), serta pengelolaan konten, media sosial, SEO, iklan digital, dan reporting bulanan.": "Optibis provides brand identity, marketing material design, website development from landing pages to custom systems, plus content, social media, SEO, digital advertising, and monthly reporting.",
  "Apakah paket dapat disesuaikan?": "Can packages be customized?",
  "Ya, semua paket dapat disesuaikan dengan kebutuhan spesifik bisnis Anda. Konsultasikan kebutuhan Anda dan kami akan merancang solusi yang tepat.": "Yes. Every package can be tailored to your specific business needs. Tell us what you need and we will design the right solution.",
  "Berapa lama pengerjaan?": "How long does delivery take?",
  "Waktu pengerjaan bervariasi tergantung layanan. Logo dan branding biasanya 2-4 minggu, website 3-8 minggu, dan Digital Growth Team beroperasi secara bulanan berkelanjutan.": "Delivery time varies by service. Logos and branding typically take 2-4 weeks, websites take 3-8 weeks, and Digital Growth Team services run monthly.",
  "Bagaimana proses revisi?": "How do revisions work?",
  "Setiap paket memiliki kuota revisi yang tercantum. Revisi dilakukan secara terstruktur melalui dashboard klien sehingga prosesnya transparan dan terdokumentasi.": "Each package includes a stated revision allowance. Revisions are managed through the client dashboard for a transparent, documented process.",
  "Apakah ada layanan bulanan?": "Do you offer monthly services?",
  "Ya, Digital Growth Team adalah layanan bulanan dimana Optibis menjadi tim digital eksternal Anda — mengelola konten, sosial media, website, SEO, iklan, dan pelaporan performa.": "Yes. Digital Growth Team is a monthly service where Optibis becomes your external digital team, managing content, social media, websites, SEO, ads, and performance reporting.",
  "Bagaimana cara memulai?": "How do I get started?",
  "Hubungi kami melalui WhatsApp atau isi form konsultasi di samping. Tim kami akan menghubungi Anda dalam 1x24 jam untuk menjadwalkan sesi konsultasi gratis.": "Contact us through WhatsApp or complete the consultation form. Our team will contact you within 24 hours to schedule a free consultation.",
  "Lengkapi data": "Complete the required fields",
  "Nama dan nomor WhatsApp wajib diisi.": "Name and WhatsApp number are required.",
  "Gagal mengirim": "Submission failed",
  "Silakan coba lagi atau hubungi kami via WhatsApp.": "Please try again or contact us through WhatsApp.",
  "Terima Kasih!": "Thank You!",
  "Tim kami akan menghubungi Anda dalam 1×24 jam melalui WhatsApp.": "Our team will contact you through WhatsApp within 24 hours.",
  "Chat Langsung via WhatsApp": "Chat Directly on WhatsApp",
  Nama: "Name",
  "Nama lengkap": "Full name",
  "Nama Bisnis": "Business Name",
  "Nama bisnis": "Business name",
  Industri: "Industry",
  "Pilih industri": "Choose an industry",
  Pilar: "Pillar",
  "Pilih pilar": "Choose a pillar",
  Kebutuhan: "Needs",
  "Jelaskan singkat kebutuhan Anda": "Briefly describe what you need",
  "Pesan Tambahan": "Additional Message",
  "Belum Tahu": "Not Sure Yet",
  Lainnya: "Other",
  "Mengirim...": "Sending...",
  "Kirim Konsultasi": "Send Consultation",
  "Siap Membangun Brand, Website, dan Pertumbuhan Digital Bisnis Anda?": "Ready to Build Your Brand, Website, and Digital Growth?",
  "Konsultasikan kebutuhan bisnis Anda secara gratis dan dapatkan rekomendasi solusi yang sesuai.": "Discuss your business needs for free and receive a solution recommendation that fits.",
  "Chat via WhatsApp": "Chat on WhatsApp",
  "Insight Terbaru": "Latest Insights",
  "Lihat Semua": "View All",
  "Semua Trending": "View All Trending",
  views: "views",
  "Viral Score": "Viral Score",
  "Video Pendek Pilihan": "Featured Short Videos",
  "Semua Video": "View All Videos",
  "Download Center & Sales Kit": "Download Center & Sales Kit",
  "Akses materi promosi resmi — company profile, katalog, ebook, template, dan branding assets. Preview gratis, download dengan login.": "Access official promotional materials including company profiles, catalogs, ebooks, templates, and brand assets. Preview for free and sign in to download.",
  Preview: "Preview",
  Download: "Download",
  "Preview Gratis": "Free Preview",
  "Download dengan Login": "Sign In to Download",
  "Share & Request Custom": "Share & Request Custom Work",
  "5 Strategi Branding yang Membuat UMKM Naik Kelas di 2026": "5 Branding Strategies to Help SMEs Level Up in 2026",
  "Branding bukan hanya soal logo. Pelajari 5 strategi konkret yang membantu UMKM Indonesia bersaing di level berikutnya.": "Branding is more than a logo. Learn five practical strategies that help Indonesian SMEs compete at the next level.",
  "Cara Membuat Landing Page yang Konversi 3x Lebih Tinggi": "How to Build a Landing Page That Converts 3x Better",
  "Struktur, copywriting, dan desain — semua harus bekerja bersama. Inilah formula yang terbukti.": "Structure, copywriting, and design must work together. Here is a proven formula.",
  "Tren Digital Marketing Indonesia 2026: Apa yang Harus Dipersiapkan?": "Indonesia Digital Marketing Trends 2026: What Should You Prepare?",
  "2026 menjadi tahun di mana AI tidak lagi pilihan, melainkan keharusan. Begini cara mempersiapkannya.": "In 2026, AI is no longer optional. Here is how to prepare your business.",
  "Formula Reels yang Viral untuk Bisnis Lokal": "A Viral Reels Formula for Local Businesses",
  "Tidak perlu ribuan follower. Dengan formula ini, Reels Anda bisa menjangkau ribuan calon klien.": "You do not need thousands of followers. This formula can help your Reels reach thousands of potential clients.",
  "SEO Lokal: Panduan Lengkap untuk Bisnis Indonesia": "Local SEO: A Complete Guide for Indonesian Businesses",
  "Startup Story: Dari 0 ke 10K Followers dalam 90 Hari": "Startup Story: From 0 to 10K Followers in 90 Days",
  "Tim Digital vs Freelancer: Mana yang Lebih Hemat?": "Digital Team vs Freelancer: Which Is More Cost Effective?",
  "Kenapa Website Cepat = Lebih Banyak Klien": "Why a Fast Website Means More Clients",
  "Content Strategy Framework: Dari Ide ke Publikasi": "Content Strategy Framework: From Idea to Publication",
  "Sponsored: Solusi All-in-One untuk Digitalisasi Bisnis": "Sponsored: An All-in-One Business Digitalization Solution",
  "Meta Ads Update 2026: Apa yang Berubah dan Bagaimana Adaptasi": "Meta Ads Update 2026: What Changed and How to Adapt",
  "Membangun Personal Branding untuk Entrepreneur": "Building a Personal Brand for Entrepreneurs",
  "Bisnis Go Digital Checklist 2026": "Business Go Digital Checklist 2026",
  "Kenapa Brand Consistency Itu Penting": "Why Brand Consistency Matters",
  "TikTok untuk Bisnis: Bukan Sekadar Dancing": "TikTok for Business: More Than Dancing",
  Skor: "Score",
  "Pilih kontak untuk chat via WhatsApp": "Choose a contact to chat on WhatsApp",
  Tutup: "Close",
  "Konsisten": "Consistent",
  "Semua aset visual mengikuti satu panduan brand yang sama.": "Every visual asset follows one consistent brand guideline.",
  Profesional: "Professional",
  "Tampilan bisnis terlihat lebih kredibel dan terpercaya.": "Your business looks more credible and trustworthy.",
  "Siap Pakai": "Ready to Use",
  "Semua file siap digunakan untuk online maupun cetak.": "Every file is ready for digital and print use.",
  "Mudah Dikelola": "Easy to Manage",
  "Brand guideline membuat tim Anda mudah membuat materi baru.": "Brand guidelines make it easy for your team to create new materials.",
  "Layanan Digital Asset": "Digital Asset Services",
  "Enam layanan utama untuk membangun identitas digital bisnis Anda dari nol.": "Six core services to build your business's digital identity from the ground up.",
  "Cara Kerja": "How It Works",
  "Proses yang transparan dari awal hingga penyerahan aset.": "A transparent process from kickoff through asset handover.",
  "Workshop untuk memahami visi, nilai, dan kepribadian brand Anda.": "A workshop to understand your brand's vision, values, and personality.",
  "Konsep & Moodboard": "Concept & Moodboard",
  "Eksplorasi arah visual dan presentasi konsep untuk persetujuan.": "Visual direction exploration and concept presentation for approval.",
  "Desain & Produksi": "Design & Production",
  "Pengerjaan semua aset digital sesuai konsep yang disetujui.": "Production of all digital assets based on the approved concept.",
  "Proses review terstruktur dengan kuota revisi yang transparan.": "A structured review process with a transparent revision allowance.",
  "Final & Handover": "Final Delivery & Handover",
  "Penyerahan file lengkap, brand guideline, dan panduan penggunaan.": "Delivery of complete files, brand guidelines, and usage instructions.",
  "Siap Membangun Identitas Digital Bisnis Anda?": "Ready to Build Your Business's Digital Identity?",
  "Konsultasikan kebutuhan branding bisnis Anda secara gratis.": "Discuss your business branding needs for free.",
  "Mudah Diperbarui": "Easy to Update",
  "CMS yang memudahkan tim Anda update konten sendiri.": "A CMS that lets your team update content independently.",
  "Dashboard intuitif untuk tim non-teknis.": "An intuitive dashboard for non-technical teams.",
  "Dibangun dengan struktur yang mudah ditemukan Google.": "Built with a structure that is easy for Google to discover.",
  "Aman & Cepat": "Secure & Fast",
  "Keamanan terjamin dan loading time optimal.": "Reliable security and optimized loading times.",
  "Layanan Website": "Website Services",
  "Enam layanan website untuk berbagai kebutuhan bisnis Anda.": "Six website services for a wide range of business needs.",
  "Proses development yang transparan dari konsep hingga launch.": "A transparent development process from concept to launch.",
  "Analisis kebutuhan, riset kompetitor, dan perencanaan struktur website.": "Needs analysis, competitor research, and website structure planning.",
  "Desain UI/UX dengan mockup untuk persetujuan sebelum development.": "UI/UX design and mockups for approval before development.",
  "Pembangunan website dengan teknologi terkini dan standar terbaik.": "Website development using current technology and best practices.",
  "Testing & Review": "Testing & Review",
  "Uji coba menyeluruh di berbagai perangkat dan browser.": "Thorough testing across devices and browsers.",
  "Deployment, training CMS, dan dokumentasi lengkap.": "Deployment, CMS training, and complete documentation.",
  "Siap Membangun Website Bisnis Anda?": "Ready to Build Your Business Website?",
  "Konsultasikan kebutuhan website Anda secara gratis.": "Discuss your website needs for free.",
  "Konten Konsisten": "Consistent Content",
  "Website Terawat": "A Well-Maintained Website",
  "Laporan Jelas": "Clear Reporting",
  "Tim Lebih Hemat": "A More Cost-Efficient Team",
  "Layanan Digital Growth Team": "Digital Growth Team Services",
  "Enam layanan utama yang dikelola secara berkelanjutan setiap bulan.": "Six core services managed continuously every month.",
  "Siklus bulanan yang berkelanjutan untuk pertumbuhan digital konsisten.": "An ongoing monthly cycle for consistent digital growth.",
  "Analisis kehadiran digital, kompetitor, dan target audience bisnis Anda.": "Analysis of your digital presence, competitors, and target audience.",
  "Penyusunan content strategy, kalender konten, dan KPI bulanan.": "Development of content strategy, content calendars, and monthly KPIs.",
  "Produksi & Publishing": "Production & Publishing",
  "Pembuatan konten, desain, copywriting, dan publishing sesuai jadwal.": "Content creation, design, copywriting, and scheduled publishing.",
  "Monitoring & Engagement": "Monitoring & Engagement",
  "Monitoring performa, engagement audiens, dan optimasi berkala.": "Performance monitoring, audience engagement, and regular optimization.",
  "Reporting & Optimization": "Reporting & Optimization",
  "Laporan bulanan dan strategy review untuk peningkatan berkelanjutan.": "Monthly reporting and strategy reviews for continuous improvement.",
  "Siap Memiliki Tim Digital Sendiri?": "Ready to Have Your Own Digital Team?",
  "Konsultasikan kebutuhan pengelolaan digital bisnis Anda secara gratis.": "Discuss your digital management needs for free.",
  "PORTOFOLIO PILAR INI": "THIS PILLAR'S PORTFOLIO",
  Proyek: "Projects",
  "Branding & website lengkap untuk agen travel premium yang ingin tampil profesional dan meningkatkan booking online.": "Complete branding and website services for a premium travel agency ready to look professional and increase online bookings.",
  "Corporate website dan brand identity untuk developer properti yang ingin menampilkan portfolio proyek dengan elegan.": "A corporate website and brand identity for a property developer presenting projects with confidence.",
  "Website booking & social media management untuk klinik mata yang ingin meningkatkan appointment online.": "A booking website and social media management for an eye clinic increasing online appointments.",
  "Branding, content management & ads untuk restoran chain yang ingin meningkatkan brand awareness dan kunjungan.": "Branding, content management, and advertising for a restaurant chain growing awareness and visits.",
  "Personal branding & portfolio website untuk konsultan bisnis yang ingin tampil profesional dan menarik klien korporat.": "Personal branding and a portfolio website for a business consultant attracting corporate clients.",
  "Company website premium dengan portfolio gallery untuk kontraktor yang ingin menampilkan proyek-proyek megah mereka.": "A premium company website with a portfolio gallery for a contractor showcasing major projects.",
  "Optibis benar-benar memahami kebutuhan bisnis kami. Dari branding sampai pengelolaan digital bulanan, semuanya ditangani dengan profesional.": "Optibis truly understands our business needs. From branding to monthly digital management, everything is handled professionally.",
  "Awalnya hanya mau bikin logo, akhirnya kami pakai semua layanan Optibis. Brand kami sekarang terlihat profesional dan konsisten di semua platform.": "We initially only wanted a logo, but ended up using all of Optibis' services. Our brand now looks professional and consistent on every platform.",
  "Website yang dibuatkan Optibis membantu kami mendapatkan klien baru. Leads masuk lebih teratur dan mudah dipantau oleh tim kami.": "The website Optibis built helps us win new clients. Leads are more organized and easier for our team to monitor.",
  "Sejak menggunakan Digital Growth Team dari Optibis, konten kami rutin, media sosial lebih aktif, dan kami bisa fokus pada operasional restoran.": "Since working with Optibis' Digital Growth Team, our content is consistent, social media is more active, and we can focus on restaurant operations.",
  Artikel: "Article",
  Galeri: "Gallery",
  "Bisnis Digital": "Digital Business",
  "min baca": "min read",
};

const MESSAGES = {
  id: {
    searchPlaceholder: "Cari produk, paket, layanan, atau berita...",
    globalSearch: "Pencarian Global",
    all: "Semua",
    products: "Produk",
    packages: "Paket",
    services: "Layanan",
    news: "Berita",
    resultFor: "Hasil untuk",
    resultsFound: "hasil ditemukan",
    noResults: "Tidak ada hasil",
    noResultsDescription: "Coba kata kunci lain atau pilih kategori yang berbeda.",
    popularSearches: "Pencarian populer",
    openResult: "Buka",
    language: "Bahasa",
    chooseLanguage: "Pilih bahasa",
    lightMode: "Gunakan mode terang",
    darkMode: "Gunakan mode gelap",
    relevantPackages: "Paket yang relevan dengan kategori {{category}}.",
    trendingDescription: "Insight terbaru untuk membantu bisnis Anda tetap relevan.",
  },
  en: {
    searchPlaceholder: "Search products, packages, services, or news...",
    globalSearch: "Global Search",
    all: "All",
    products: "Products",
    packages: "Packages",
    services: "Services",
    news: "News",
    resultFor: "Results for",
    resultsFound: "results found",
    noResults: "No results found",
    noResultsDescription: "Try another keyword or choose a different category.",
    popularSearches: "Popular searches",
    openResult: "Open",
    language: "Language",
    chooseLanguage: "Choose language",
    lightMode: "Use light mode",
    darkMode: "Use dark mode",
    relevantPackages: "Packages relevant to the {{category}} category.",
    trendingDescription: "Fresh insights to help your business stay relevant.",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem("optibis-language") || "id");

  const setLanguage = useCallback((value) => {
    const next = value === "en" ? "en" : "id";
    localStorage.setItem("optibis-language", next);
    setLanguageState(next);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback((key, variables = {}) => {
    let value = MESSAGES[language]?.[key] || MESSAGES.id[key] || key;
    Object.entries(variables).forEach(([name, replacement]) => {
      value = value.replace(`{{${name}}}`, replacement);
    });
    return value;
  }, [language]);

  const tr = useCallback((text) => {
    if (language === "id") return text;
    return TEXT_TRANSLATIONS[text] || text;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t, tr }), [language, setLanguage, t, tr]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
